use crate::displayed_item::DisplayedItem;
use crate::state::UserState;
use crate::wave_source::WaveSource;
use crate::wave_container::VariableRefExt;

/// Generate a command file string that restores a simplified version of the
/// current state. The simplified state is meant to capture basic
/// characteristics of the current state in a more minimal way.
pub fn generate_command_string(state: &UserState) -> String {
    let mut commands = Vec::new();

    let version = env!("CARGO_PKG_VERSION");
    let git_hash = option_env!("VERGEN_GIT_DESCRIBE")
        .or(option_env!("VERGEN_GIT_SHA"))
        .unwrap_or("unknown");
    commands.push(format!("# Generated by Surfer v{} ({})", version, git_hash));

    if let Some(waves) = &state.waves {
        // Load the wave file, skip if unknown origin. This would mean that one
        // could still combine the generated command file with some out of band
        // loading.
        match &waves.source {
            WaveSource::File(path) => {
                if path.is_absolute() {
                    commands.push(format!("load_file {}", path));
                } else {
                    commands.push(format!("# load_file skipped for relative path: {}", path));
                }
            }
            WaveSource::Url(url) => {
                commands.push(format!("load_url {}", url));
            }
            _ => {
                commands.push("# Unknown or unsupported wave source".to_string());
            }
        }

        // Add variables and items We iterate through the displayed items tree
        // to maintain order.
        for node in waves.items_tree.iter() {
            if let Some(item) = waves.displayed_items.get(&node.item_ref) {
                match item {
                    DisplayedItem::Variable(var) => {
                        // variable_add <full_path>
                        commands.push(format!("variable_add {}", var.variable_ref.full_path_string()));
                        
                        // Apply styling to the just-added variable.
                        if let Some(color) = &var.color {
                            commands.push(format!("item_set_color {}", color));
                        }
                        if let Some(bg_color) = &var.background_color {
                            commands.push(format!("item_set_background_color {}", bg_color));
                        }
                        if let Some(format) = &var.format {
                            commands.push(format!("item_set_format {}", format));
                        }
                        if let Some(manual_name) = &var.manual_name {
                            commands.push(format!("item_rename {}", manual_name));
                        }
                    }
                    DisplayedItem::Divider(div) => {
                        let name = div.name.as_deref().unwrap_or("");
                        commands.push(format!("divider_add {}", name));
                       
                        // Apply divider styling.
                        if let Some(color) = &div.color {
                            commands.push(format!("item_set_color {}", color));
                        }
                        if let Some(bg_color) = &div.background_color {
                            commands.push(format!("item_set_background_color {}", bg_color));
                        }
                    }
                    DisplayedItem::TimeLine(tl) => {
                        commands.push("timeline_add".to_string());
                         if let Some(color) = &tl.color {
                            commands.push(format!("item_set_color {}", color));
                        }
                        if let Some(bg_color) = &tl.background_color {
                            commands.push(format!("item_set_background_color {}", bg_color));
                        }
                         if let Some(name) = &tl.name {
                             commands.push(format!("item_rename {}", name));
                         }
                    }
                    DisplayedItem::Marker(m) => {
                        // Handled below.
                    }
                    DisplayedItem::Group(g) => {
                        // We don't have a reliable 'add_group' command for
                        // custom groups yet so just add comment.
                        commands.push(format!("# Group: {}", g.name));
                    }
                    DisplayedItem::Stream(s) => {
                         commands.push(format!("stream_add {}", s.transaction_stream_ref.name));
                    }
                    DisplayedItem::Placeholder(p) => {
                         commands.push(format!("# Placeholder: {}", p.variable_ref.full_path_string()));
                    }
                }
            }
        }
    }
    
    // Restore cursor.
    if let Some(cursor) = &state.waves.as_ref().and_then(|w| w.cursor.clone()) {
        commands.push(format!("cursor_set {}", cursor));
    }
    
    // Restore markers.
    if let Some(waves) = &state.waves {
        for (id, time) in &waves.markers {
             commands.push(format!("marker_set {} {}", id, time));
        }
    }

    // TODO: Restore view (zoom/scroll). Simply zoom fit for now.
    commands.push("zoom_fit".to_string());

    commands.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::UserState;
    use crate::wave_source::WaveSource;
    use crate::displayed_item::{DisplayedItem, DisplayedVariable};
    use crate::wave_data::WaveData;
    use crate::wave_container::{VariableRef, ScopeRef, ScopeRefExt, VarId};
    use crate::displayed_item_tree::{TargetPosition, ItemIndex};
    use crate::displayed_item::DisplayedItemRef;
    use crate::variable_name_type::VariableNameType;
    use camino::Utf8PathBuf;

    #[test]
    fn test_generate_simple_command_string() {
        let mut state = UserState::default();
        let mut waves = WaveData::default();
        
        waves.source = WaveSource::File(Utf8PathBuf::from("/tmp/test.vcd"));
        
        let var_ref = VariableRef {
             name: "clk".to_string(),
             path: ScopeRef::from_hierarchy_string("top"),
             id: VarId::default(),
        };
        
        let disp_var = DisplayedVariable {
            variable_ref: var_ref.clone(),
            info: Default::default(),
            color: Some("Red".to_string()),
            background_color: None,
            display_name: "clk".to_string(),
            display_name_type: VariableNameType::Local,
            manual_name: None,
            format: Some("Hex".to_string()),
            field_formats: vec![],
            height_scaling_factor: None,
            analog: None,
        };
        
        let item_ref = DisplayedItemRef(0);
        waves.displayed_items.insert(item_ref, DisplayedItem::Variable(disp_var.clone()));
                
        waves.items_tree.insert_item(item_ref, TargetPosition { before: ItemIndex(0), level: 0 }).unwrap();
        
        let placeholder = disp_var.into_placeholder();
        let item_ref_2 = DisplayedItemRef(1);
        waves.displayed_items.insert(item_ref_2, DisplayedItem::Placeholder(placeholder));
        waves.items_tree.insert_item(item_ref_2, TargetPosition { before: ItemIndex(1), level: 0 }).unwrap();
        
        state.waves = Some(waves);
        
        let cmd_str = generate_command_string(&state);
        
        assert!(cmd_str.starts_with("# Generated by Surfer v"));
        assert!(cmd_str.contains("load_file /tmp/test.vcd"));
        assert!(cmd_str.contains("variable_add top.clk"));
        assert!(cmd_str.contains("item_set_color Red"));
        assert!(cmd_str.contains("item_set_format Hex"));
        assert!(cmd_str.contains("# Placeholder: top.clk"));
    }
}
