//! Configuration Metadata - AUTO-GENERATED AT COMPILE TIME
//!
//! This module is generated by `build.rs` from the template in `config_metadata_template.rs`.
//! Do not edit this file directly. Instead:
//!
//! 1. Edit the configuration structures in `config.rs` to add/remove fields
//! 2. Update `config_metadata_template.rs` to describe the new fields
//! 3. Rebuild the project - the metadata will be automatically regenerated
//!
//! # Access the Generated Metadata
//!
//! The generated metadata is available at compile-time via the `config_metadata` module:
//!
//! ```ignore
//! use libsurfer::config_metadata::{LayoutConfigMetadata, ConfigMetadata};
//!
//! let layout_meta = LayoutConfigMetadata::metadata();
//! println!("Layout fields: {}", layout_meta.fields.len());
//! ```

// Re-export the generated metadata for convenience
pub use crate::config_metadata::*;
